version: '3'
services:
  bottaxi:
    build: .
    container_name: bottaxi
    ports:
      - "3000:3000" # Substitua por suas portas corretas
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
    restart: always
